export const caseStudies = [
  {
    slug: "cmms",
    number: "01",
    tag: "CMMS",
    industry: "Power Industry",
    title: "Centralised Maintenance Management System",
    metric: "Eliminated unplanned downtime across distributed generator fleet",
    problem: "Manual maintenance tracking across multiple SCADA-connected generator sites — inefficient, error-prone, with no cross-site visibility.",
    solution: "Automated scheduling engine with SCADA integration, role-based dashboards, and real-time email alerting for proactive maintenance.",
    stack: ["Angular", "Spring Boot", "MS SQL", "On-Premises"],
    year: "2024",
    type: "Enterprise Platform",
    overview:
      "A large power utility operating multiple generator sites faced growing operational risk from manual, paper-based maintenance workflows. Faults were being missed, schedules were inconsistent, and there was no unified view across sites. We were brought in to build a system that would bring order to a fragmented, high-stakes environment.",
    challenges: [
      "No single source of truth for maintenance schedules across distributed sites",
      "SCADA systems at each site operated in silos with no integration layer",
      "Field teams relied on spreadsheets, leading to missed preventive tasks",
      "Management had no real-time visibility into asset health or maintenance status",
    ],
    outcomes: [
      "Zero unplanned downtime incidents in the 12 months post-deployment",
      "Maintenance task completion rate increased from 61% to 97%",
      "Automated scheduling reduced administrative overhead by 40%",
      "Real-time dashboards adopted by operations teams across all sites",
    ],
  },
  {
    slug: "ddn",
    number: "02",
    tag: "DDN",
    industry: "Smart City",
    title: "Digital Door Number System",
    metric: "City-scale QR property identification deployed across thousands of properties",
    problem: "No efficient way to coordinate large-scale installation teams, verify property ownership, or monitor smart city rollout progress.",
    solution: "Web platform for QR artefact generation and installation monitoring, plus a Flutter mobile app for field teams.",
    stack: ["Angular", "Spring Boot", "Flutter", "PostgreSQL", "AWS"],
    year: "2023",
    type: "Mobile + Web",
    overview:
      "A municipal authority needed to assign unique digital identities to every property in the city as part of a broader smart city initiative. The challenge wasn't just generating QR codes — it was coordinating hundreds of field installers, verifying ownership, and giving administrators live progress visibility across an entire city.",
    challenges: [
      "Coordinating and tracking thousands of field installations across city zones",
      "Verifying property ownership records against existing municipal databases",
      "Generating tamper-evident QR artefacts tied to specific property records",
      "Providing real-time rollout progress to city administrators",
    ],
    outcomes: [
      "Full city-wide rollout completed ahead of schedule",
      "Field team productivity improved with offline-capable mobile app",
      "Ownership verification errors reduced by 85% vs. manual process",
      "Live progress dashboard adopted by city planning department",
    ],
  },
  {
    slug: "las",
    number: "03",
    tag: "LAS",
    industry: "Government",
    title: "Land Acquisition Management System",
    metric: "Unified multi-agency land records with full audit trail",
    problem: "Land parcel data scattered across disconnected sources; ownership, litigation, and payment workflows had no central governance.",
    solution: "Secure centralised platform with revenue record integration, owner mapping, litigation management, and end-to-end acquisition workflow.",
    stack: ["Angular", "Spring Boot", "PostgreSQL", "On-Premises"],
    year: "2023",
    type: "Gov. Platform",
    overview:
      "A state government agency responsible for land acquisition lacked a unified system to manage the complex, multi-party workflows involved — from initial survey through compensation to legal completion. Data lived across revenue departments, courts, and district offices, creating governance gaps and delays.",
    challenges: [
      "Land records existed in disconnected systems across multiple government departments",
      "No unified view of owner mapping, litigation status, and payment history per parcel",
      "Audit requirements demanded complete traceability of every action and decision",
      "Sensitive data required strict access controls and on-premises deployment",
    ],
    outcomes: [
      "Full acquisition lifecycle now managed in a single auditable platform",
      "Inter-agency data reconciliation time reduced from weeks to hours",
      "Legal dispute tracking integrated directly into land parcel records",
      "Adopted by multiple district offices with role-based access control",
    ],
  },
  {
    slug: "wealthsys",
    number: "04",
    tag: "WealthSys",
    industry: "FinTech",
    title: "Wealth Analysis Platform",
    metric: "Key revenue driver — improved client acquisition for CA firm",
    problem: "HNI wealth distributed across multiple segments with no centralised system; manual reporting was slow and inconsistent.",
    solution: "Custom analytics platform with individual wealth classification schemes, balance sheet mapping, and financial performance insights.",
    stack: ["Angular", "Spring Boot", "PostgreSQL", "AWS"],
    year: "2024",
    type: "Analytics",
    overview:
      "A chartered accountancy firm serving high-net-worth individuals needed a competitive edge in client reporting. Their advisors were spending hours manually consolidating data across equity, real estate, and debt instruments into presentation-ready reports. We built a platform that did this automatically — and turned it into a client acquisition tool.",
    challenges: [
      "HNI wealth spread across equity, debt, real estate, and alternative instruments with no unified view",
      "Manual consolidation of portfolio data took advisors 4–6 hours per client per quarter",
      "No standardised classification scheme for wealth segmentation across clients",
      "Existing reports were inconsistent and lacked the depth that HNI clients expected",
    ],
    outcomes: [
      "Report generation time reduced from hours to under 5 minutes",
      "Platform became a key differentiator in pitching to new HNI prospects",
      "Wealth classification engine adopted as internal standard across all client relationships",
      "Client retention improved as advisors could provide deeper, faster insights",
    ],
  },
];

export type CaseStudy = typeof caseStudies[0];
